#!/bin/sh -e

if [ -z ${FLUXION_RESOURCE_RC_NOOP} ]; then
    if [ $(flux getattr rank) -eq 0 ]; then
        flux module reload -f sched-fluxion-resource \
            ${FLUXION_RESOURCE_OPTIONS:-"load-allowlist=node,core,gpu"} \
            satisfiability=false
    fi
fi

if [ -z ${FLUXION_RESOURCE_RC_NOOP} ]; then
    # load on all ranks
    flux module reload -f --name=sched-fluxion-satisfiability sched-fluxion-resource \
        ${FLUXION_RESOURCE_OPTIONS:-"load-allowlist=node,core,gpu"} \
        satisfiability=true 
fi

if [ -z ${FLUXION_QMANAGER_RC_NOOP} ]; then
    if [ $(flux getattr rank) -eq 0 ]; then
        flux module reload -f sched-fluxion-qmanager ${FLUXION_QMANAGER_OPTIONS}
    fi
fi
