#!/bin/bash

#	--logdest=cmbd.log \

./cmbd --verbose --rank=0 --size=1 --hostlist=localhost \
    --plugins=modctl,api,barrier,kvs,log,hb,job,event,log,sim,submit,sim_sched,sim_exec \
    kvs:conf.hb.period-sec=1.5 \
    kvs:conf.log.reduction-timeout-msec=100 \
    kvs:conf.log.circular-buffer-entries=100000 \
    kvs:conf.log.persist-level=info \
	sim_sched:rdl-conf=conf/cab.lua \
	submit:job-csv=simulator/job_data/2014-06-01.csv
