coverage:
 precision: 1
 round: down
 range: "65...100"
 ignore:
 - "**/test/*.c"
 - "**/tests/*.c"
 - "src/common/libtap/.*"
 - "src/common/libutil/json.hpp"

 # Allow coverage to drop up to 0.1%
 status:
  project:
   default:
    threshold: .1

comment:
  layout: "header, diff, changes, tree"
  behavior: new
