#!/bin/bash
#
#

prog=`basename $0`

say()  { echo "$prog: $@"; }
warn() { echo >&2 "$prog: Warning: $@"; }
usage() {
    echo >&2 "Usage: $0 '[flux-core-top-builddir]'"
    exit 1
}

if test $# -eq 1; then
    say Configuring for flux-core builddir of $1
    rm -f .build
    ln -sf $1 .build
    if ! test -d $1; then
        warn "$1 is not a directory"
    fi
elif test $# -eq 0; then
    say Configuring for installed flux-core
    rm -f .build
    if ! pkg-config --exists flux-core; then
        warn "pkg-config could not find flux-core"
	usage
    fi
else
    usage
fi
