#!/bin/bash

gdb --args ./cmbd --verbose --rank=0 --size=1 --hostlist=localhost \
    --plugins=modctl,api,barrier,kvs,log,hb,job,event,log,sim,submit,sim_sched,model_exec \
    kvs:conf.hb.period-sec=1.5 \
    kvs:conf.log.reduction-timeout-msec=100 \
    kvs:conf.log.circular-buffer-entries=100000 \
    kvs:conf.log.persist-level=debug \
	sim_sched:rdl-conf=conf/hype.lua


#	   --logdest=cmbd.log \
