#!/bin/bash

ARGS="--verbose --rank=0 --size=1 --hostlist=localhost \
		--plugins=modctl,api,barrier,kvs,log,hb,job,event,log,sim,submit,sim_sched,sim_exec \
		kvs:conf.hb.period-sec=1.5 \
		kvs:conf.log.reduction-timeout-msec=100 \
		kvs:conf.log.circular-buffer-entries=100000 \
		kvs:conf.log.persist-level=debug \
		sim_sched:rdl-conf=conf/hype.lua \
		submit:job-csv=simulator/job_data/hype.csv"

#	   --logdest=cmbd.log \

if [ "$1" == "totalview" ]; then
	totalview ./cmbd -a $ARGS
elif [ "$1" == "memscape" ]; then
	memscape ./cmbd -a $ARGS
else
	gdb --args ./cmbd $ARGS
fi
