#!/bin/bash -e
#
# If sched-fluxion-qmanager is not installed into flux-core's $prefix,
# one should set FLUX_RC_EXTRA environment variable to flux-sched's $prefix/etc/flux
# so that flux start can automatically execute sched-fluxion-qmanager's
# runlevel 1 and 3.
#
# In addition, users can set FLUXION_QMANAGER_OPTIONS if they want flux
# to load in the queue manager service module with non-default options.
#
# Finally, if FLUXION_QMANAGER_RC_NOOP=1, flux-core
# won't load in or remove sched-fluxion-qmanager as part of runlevel 1 and 3.
#
# Note that we use "flux reload -f sched-fluxion-qmanager"
# instead of "flux load sched-fluxion-qmanager" to ease our testing.
# Without this, some of the in-tree tests can fail when flux-sched is already
# installed with flux-core. These installed rc1 scripts are
# executed first and disallow the "in-tree" modules from loading.
# We now use "flux reload -f sched-fluxion-qmanager" so that
# when these failing tests load it via FLUX_RC_EXTRA,
# the in-tree version can be loaded.

test $(flux getattr rank) -eq 0 || exit 0

if [ -z ${FLUXION_QMANAGER_RC_NOOP} ]; then
    flux module remove -f sched-simple
    flux module reload -f sched-fluxion-qmanager ${FLUXION_QMANAGER_OPTIONS}
fi

