#!/bin/bash -e
#
# If qmanager is not installed into flux-core's $prefix,
# one should set FLUX_RC_EXTRA environment variable to flux-sched's $prefix/etc/flux
# so that flux start can automatically execute qmanager's runlevel 1 and 3.
#
# In addition, users can set FLUX_QMANAGER_OPTIONS if they want flux
# to load in the queue manager service module with non-default options.
#
# Finally, if FLUX_QMANAGER_RC_NOOP=1, flux-core
# won't load in or remove qmanager as part of runlevel 1 and 3.
#

if [ -z ${FLUX_QMANAGER_RC_NOOP} ]; then
    flux module remove sched-simple
    flux module load qmanager ${FLUX_QMANAGER_OPTIONS}
fi

