#!/bin/bash -e
#
# If qmanager is not installed into flux-core's $prefix,
# one should set FLUX_RC_EXTRA environment variable to flux-sched's $prefix/etc/flux
# so that flux start can automatically execute qmanager's runlevel 1 and 3.
#
# In addition, users can set FLUX_QMANAGER_OPTIONS if they want flux
# to load in the queue manager service module with non-default options.
#
# Finally, if FLUX_QMANAGER_RC_NOOP=1, flux-core
# won't load in or remove qmanager as part of runlevel 1 and 3.
#
# Note that we use "flux reload -f qmanager" instead of "flux load qmanager"
# to ease our testing.
# Without this, some of the in-tree tests can fail when flux-sched is already
# installed with flux-core. These installed rc1 scripts are
# executed first and disallow the "in-tree" modules from loading.
# We now use "flux reload -f qmanager" so that when these failing tests
# load it via FLUX_RC_EXTRA, the in-tree version can be loaded.

if [ -z ${FLUX_QMANAGER_RC_NOOP} ]; then
    flux module remove -f sched-simple
    flux module reload -f qmanager ${FLUX_QMANAGER_OPTIONS}
fi

