#!/bin/bash -e
#
# If sched is not installed into flux-core's $prefix,
# one should set FLUX_RC_EXTRA environment variable to flux-sched's $prefix/etc/flux
# so that flux start can automatically execute sched's runlevel 1 and 3.
#
# In addition, users can set FLUX_SCHED_OPTIONS if they want flux
# to load in the sched module with non-default options.
# (e.g., FLUX_SCHED_OPTIONS="plugin=sched.backfill" will cause
# flux to load the sched module with the backfil scheduling plugin.
#
# Finally, if FLUX_SCHED_RC_NOOP=1, flux-core
# won't load in or remove sched as part of runlevel 1 and 3.
#

if [ -z ${FLUX_SCHED_RC_NOOP} ]; then
    flux module load -r 0 sched ${FLUX_SCHED_OPTIONS}
fi

