#!/bin/sh

flux module remove -f sched-fluxion-feasibility

if [ $(flux getattr rank) -eq 0 ]; then
    flux module remove -f sched-fluxion-qmanager
    flux module remove -f sched-fluxion-resource
fi

