#!/bin/bash

if command -v pre-commit 2>&1 > /dev/null ; then
  pre-commit run --all-files
else
  echo "pre-commit not found, please install it, if unsure how use pip install -r scripts/requirements-dev.txt"
fi
