#!/bin/bash

if command -v black 2>&1 > /dev/null ; then
  # awk cmd copied from:
  # https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang
  find src t -path "src/python/fluxion/jsongraph" -prune -o \
        -type f \( -name "*.py" -print -o \
        -exec awk ' /^#!.*python/{print FILENAME} {nextfile}' {} + \) \
      | xargs black
else
  echo "black not found, python left unformatted"
fi

find resource qmanager src/ -name '*.h' -o -name '*.c' -o -name '*.cpp' -o -name '*.hpp' |
  grep -v yggdrasil |
  grep -v 'json.hpp' |
  grep -v libtap |
  xargs -P 8 -n 1 clang-format -i
